name: daily_flutter
description: >
  Flutter plugin for Daily.

  The Daily Client SDK allows you to build video and audio calling into your Flutter applications.
version: 0.20.0
homepage: https://daily.co

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  collection: ^1.15.0
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.14
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  logging: ^1.0.0
  meta: ^1.3.0
  permission_handler: ^11.3.1
  plugin_platform_interface: ^2.1.3
  synchronized: ^3.0.0+3

dev_dependencies:
  build_runner: ^2.3.3
  dartdoc:
  ffigen: ^12.0.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  version_gen: ^1.0.1

flutter:
  plugin:
    platforms:
      android:
        package: co.daily.daily_flutter
        pluginClass: DailyFlutterPlugin
      ios:
        pluginClass: DailyFlutterPlugin

version_gen:
  path: lib/src
